---
# Ansible playbook to run Linux Centos/RHEL Update and restart, if required
#

- hosts: all
  become: true
  tasks:
  - name: Upgrade all installed packages for CentOS
    yum:
      name: '*'
      state: latest
      
  - name: Check if a reboot is needed on all servers
    register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

  - name: Reboot when there is a change
    shell: "sleep 5 && reboot"
    async: 1
    poll: 0
    become: true
    ignore_errors: true
    when: reboot_required_file.stat.exists

  - name: wait for 10 seconds
    pause:
      seconds: 10

  - name: wait for the system to reboot
    wait_for_connection:
      connect_timeout: 20
      sleep: 5
      delay: 5
      timeout: 60
      
