---
# Ansible playbook to run Linux Centos/RHEL Update and restart, if required
#

- hosts: all
  become: true
  tasks:
  - name: Upgrade all installed packages for CentOS
    yum:
      name: '*'
      state: latest

  - name: Reboot when there is a change
    shell: "sleep 5 && reboot"
    async: 1
    poll: 0
    become: true
    ignore_errors: true

  - name: wait for 10 seconds
    pause:
      seconds: 10

  - name: wait for the system to reboot
    wait_for_connection:
      connect_timeout: 20
      sleep: 5
      delay: 5
      timeout: 60
