---
# Ansible playbook reboot Linux Server
#

- hosts: all
  become: true
  become_user: root
  tasks:
    - name: Reboot 
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
